### ISSUE TITLE
thymeleaf 에서 정적자원 가져오기.

### ISSUE THREAD

**Issue by devarchi33** [DomainDriven/lacs#1]

**Comment by jb7959** [comment]
src/main/resources/META-INF/
src/main/resources/resources/
src/main/resources/static/
src/main/resources/public/

스프링 부트에서 이렇게 접근이 가능하다고 합니다.
http://stackoverflow.com/questions/29562471/springboot-with-thymeleaf-css-not-found

저는 static 사용했고, 아래와 같은 경로에 styles.css 를 넣어 주었습니다.  
src/main/resources/static/css/styles.css 

호출은 타임리프에서 아래와 같이 호출했구요. 
<link rel="stylesheet" href="css/styles.css" /> 

다음 작업으로 아래와같이 타임리프 문법을 이용해 볼 예정입니다. (이점은???)
"@{/css/style.css}"

**Comment by devarchi33** [comment]
14fd3dd21676f64b3f9de796d6c4b14dd1b4333e

주의!
registry.addResourceHandler("/static/**").addResourceLocations("classpath:/static/"); 

addResourceLocations 의 인자를 classpath:/static/*, classpath:/static/** 로 전달하면 경로 인식이 안됨.
