### ISSUE TITLE
[B] uploadingProgress 모달 파일 존재하지 않는 오류.

### ISSUE THREAD

**Issue by devarchi33** [DomainDriven/lacs#35]
Error resolving template "fragments/modal/uploadingProgress", template might not exist or might not be accessible by any of the configured Template Resolvers (fragments/pages/detail/makingPoster:93)

uploadingProgress 모달 파일이 없는 것 같아요 포스터 제작 화면이 열리지 않네요;;;

**Comment by jb7959** [comment]
헉.. 연구실에서 커밋이 잘못됬나봐요 ; 금욜날 업데이트 할께요. ㅠㅠㅠ
